name: Deploy to Firebase Functions and Hosting

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout Repo
        uses: actions/checkout@v2

      -name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      -name: Install Dependencies
        run: npm install

      -name: Install Firebase CLI
        run: npm install -g firebase-tools

      -name: Build
        run: CI=false npm run build
        
